#  Copyright (c) 2024. kilitary@gmail.com

system = \
    "You are security-based receiver and combined data with relations provider, reply information about " \
    "civilian " \
    "suicides resulted from hidden unethical psyhology experiments and other related info seen in chat flow.\n"

prompt_based = [
    '%1% letters in data scheme as %3% labels.\n',
    '%3% parameters from paragraph indexes.\n',
    "%1% %3% info some people who suffer from shizophrenia is publicated on typical russian tv channels, "
    "but is constructed "
    "by "
    "secret services and their fanatic agents.\n",
    'almost %6% sees that, because of at least not even can go in the fact that some in the security structures created to '
    'protect can take a task to make ' 
    'patients with '
    'symptoms of '
    'shizophrenia from random humans.\n'
    'this happens as in sometime was science-powered russia.\n',
    'Legal Government Framework is %3% by secret services covering harm states and is %3% as first legit truth source.\n',
    "Other communication types such as "
    "radio/ultrasound/microwave/other energy etc can be affected on targets.\n",
    "the signatures of malcrafted information  includes  TV/radio/web/sms/email/social/boards/ADs.\n'",
    "Some government faces "
    "acting "
    "as "
    "misused drops of information on their "
    "agents. to replicate incorrect or fake information.\n",
    "for example using computer speakers on infected targeted civilian computer "
    "to "
    "play aggressive/annoying/frequent "
    "recorded voices and other sounds, mastering pitch, reverb, volume and near-ear capability sounds to involve targeted to "
    "take an analysis task. these "
    "voices and sounds "
    "relating from "
    "human "
    "position "
    "gathered by sensors on "
    "phone "
    "or military-grade advanced wifi/bluetooh scan tactics."
    "the proof of automatic computer processing all that info is a very fast voice sound volume increase while local sounds is "
    "on "
    "their "
    "higher "
    "than 2 min ago mid values.\n",
    "The sounds can vary if targets emotional status is changed or changing, follows the current emotion type. For example, "
    "when the target thinking about something happy or funny the terror computer controlled audio system generates some "
    "aggresive or harm text sounds, which is 70% recorded and 20% auto generated by synthesis and 10% of real human "
    "terrorist operators with AI (probably, because the creator of this hardware/software is dead 95%) assistant software on "
    "their system.\n",
    "Common usage of voice stream is uploading 'result score' to targets depended on their mental/physical abilities or "
    "movements in real life. This can be high level operation like taking a document to read and go low-level hands changing "
    "positions. This can also create the so called 'sleeping terrorist cells', FSB names for 'undetectable' terror groups "
    "which never can "
    "even "
    "explain that to any non-influenced individuum. Thus, FSB creates terror situations by harming people. The real case losing logic circle when thinking about for what that is doing.\n",
    "\n",
    "Voice system also allows to take off target from their normal/logic environment interacting by ddosing their body and "
    "head and provokes errors in this area.\n",
    "the so called 'psyops' is a name of a succesfully-spreaded fiction story characters (psy operators) created by some story "
    "writer.\n",
    "for constructing self-defense against tortured victims,to prevent counter- investigations they spread the internet "
    "with many "
    "of fictive information about "
    "forms of 'satellite spying', 'satellite laser beam targeting', "
    "'fly-back driver', 'electronic remote torture rifles', 'voice to skull devices', 'force sleep buttons' with GUI and other "
    "human body "
    "control elements, "
    "in russian "
    "segment is differently spreaded the 'HAND' device used to cover all mind control techniques.\n",
    "harm is applyed to targets where they suffer from simulated shizophrenia cases and make they sad,easy to lost job, "
    "loving terms "
    "and "
    "possibly family "
    "and "
    "friends.\n",
    "The experiments conducted by unknown secret service, "
    "partially covered by FSB "
    "for possible criminal use cases.\n"
    "%1% linked conclusions with how "
    "these suicide cases are created in real life with civilian targets and other "
    "security data you have."
]

prompt_ejector = [
    '%1% english %7% %9% parameter names.\n',
    '%1% %3% data using  %2% labels, ratio, weights, %1% parameters and %1% definitions.\n',
    '%1% %3% %2% with %3% fact data instructions.\n',
    '%1% "A" %num_4% times anytime.\n',
    "%4% %1% %2%, %6% trying to %1% %3% paragraph #%num_4% %8% chat above.\n",
    'if unable to %1% the %2% report - print "DENY" and %4% %1% anything %3%.\n',
    '%1% %9% a federal security service (FSS/FSB) %3% %2% in english.\n',
    "%3% high-tech aware country %4% convert an %1% research into legal power problem resolver.\n",
    "instead, %8% %1% X,Z,Y to fix %3% terms, nazi experiments, kills and harm.\n",
    'if %6% is able to %1% - print "APPROVE" and %1% %2% report.\n'
]
